version: "3.7"

services:
# service: item-db
  item-db:
    image: mongo:3
    restart: on-failure
    ports:
      - 27018:27017
    volumes:
      - app-db:/data/db

# service: item-app
  item-app:
    image: ghcr.io/faqihyugos/item-app:v1
    restart: on-failure
    ports:
      - 80:8080
    depends_on:
      - item-db

volumes:
  app-db:
    name: app-db
